# Generated by Django 3.2.8 on 2023-06-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='Serial_number',
            field=models.IntegerField(unique=True),
        ),
    ]
